apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
spec:
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: http
  selector:
    app: admin
  type: ClusterIP
